package org.drools.examples.testpackage

import java.lang.String;
import java.util.List;
import io.silverware.demos.devconf.kjar.*;

global java.util.List commands;
global java.util.List mobileStatus;

declare MoodCommand
  @expires( 2m )
  @role( event )
end

declare AirConditioningCommand
  @expires( 2m )
  @role( event )
end

declare DoorCommand
  @expires( 2m )
  @role( event )
end

declare FireplaceCommand
  @expires( 2m )
  @role( event )
end

declare LightCommand
  @expires( 2m )
  @role( event )
end

declare MediaCenterCommand
  @expires( 2m )
  @role( event )
end

rule "Day mood command"
when
   $mood: MoodCommand(mood == MoodCommand.Mood.DAY) from entry-point "acutors"
then
   System.out.println("Processing mood day");
   commands.add("l0"); // all led off
   commands.add("FC"); // fireplace cold
   commands.add("CO"); // tv off
end

rule "Evening mood command"
when
   $mood: MoodCommand(mood == MoodCommand.Mood.EVENING) from entry-point "acutors"
then
   System.out.println("Processing mood evening");
   commands.add("lE"); // all led on
   commands.add("FH"); // fireplace heat
   commands.add("CN"); // tv news
   commands.add("L10;r;30\n10;g;30\n10;b;30\n11;r;30\n11;g;30\n11;b;30\n14;r;30\n14;g;30\n14;b;30"); // set leds
end

rule "Sleep mood command"
when
   $mood: MoodCommand(mood == MoodCommand.Mood.SLEEP) from entry-point "acutors"
then
   System.out.println("Processing mood sleep");
   commands.add("l0"); // all led off
   commands.add("FC"); // fireplace cold
   commands.add("CO"); // tv off
   commands.add("DF0"); // front door close
   commands.add("DR0"); // window close
   commands.add("L3;r;30\n3;g;30\n3;b;30\n4;r;30\n4;g;30\n4;b;30\n7;r;30\n7;g;30\n7;b;30\n8;r;30\n8;g;30\n8;b;30"); // set leds
end

rule "Romantic mood command"
when
   $mood: MoodCommand(mood == MoodCommand.Mood.ROMANTIC) from entry-point "acutors"
then
   System.out.println("Processing mood romantic");
   commands.add("lR"); // all led romantic
   commands.add("FH"); // fireplace heat
   commands.add("CR"); // tv romantic
   commands.add("DF0"); // front door close
   commands.add("DR0"); // window close
end

rule "AC On/Off"
when
  $ac: AirConditioningCommand() from entry-point "acutors"
then
  System.out.println("Processing AC On/Off");
  commands.add($ac.toString());
end

rule "Fireplace On/Off"
when
  $fire: FireplaceCommand() from entry-point "acutors"
then
  System.out.println("Processing Fireplace On/Off");
  commands.add($fire.toString());
end

rule "Doors Open/Close"
when
  $door: DoorCommand() from entry-point "acutors"
then
  System.out.println("Processing Doors Open/Close");
  commands.add($door.toString());
end

rule "Media Center Mode"
when
  $media: MediaCenterCommand() from entry-point "acutors"
then
  System.out.println("Processing Media Center Mode");
  commands.add($media.toString());
end

rule "Light Bedroom On"
when
  $light: LightCommand(place == LightCommand.Place.BEDROOM, state == LightCommand.State.ON) from entry-point "acutors"
then
  System.out.println("Processing Light Bedroom On");
  commands.add("L");
end
