apiVersion: v1
kind: Service
metadata:
  name: cluster-cdi-helloworld
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    project: cluster-cdi-helloworld
  type: LoadBalancer

